spring:
  datasource:
    url: jdbc:mysql://172.23.51.114:3306/flyway?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root

  flyway:
    baseline-on-migrate: true