-- liquibase formatted sql

-- changeset 82431:1666748033857-1
CREATE TABLE QRTZ_BLOB_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(190) NOT NULL, TRIGGER_GROUP VARCHAR(190) NOT NULL, BLOB_DATA BLOB NULL, CONSTRAINT PK_QRTZ_BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP));

-- changeset 82431:1666748033857-2
CREATE TABLE QRTZ_CALENDARS (SCHED_NAME VARCHAR(120) NOT NULL, CALENDAR_NAME VARCHAR(190) NOT NULL, CALENDAR BLOB NOT NULL, CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (SCHED_NAME, CALENDAR_NAME));

-- changeset 82431:1666748033857-3
CREATE TABLE QRTZ_CRON_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(190) NOT NULL, TRIGGER_GROUP VARCHAR(190) NOT NULL, CRON_EXPRESSION VARCHAR(120) NOT NULL, TIME_ZONE_ID VARCHAR(80) NULL, CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP));

-- changeset 82431:1666748033857-4
CREATE TABLE QRTZ_FIRED_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, ENTRY_ID VARCHAR(95) NOT NULL, TRIGGER_NAME VARCHAR(190) NOT NULL, TRIGGER_GROUP VARCHAR(190) NOT NULL, INSTANCE_NAME VARCHAR(190) NOT NULL, FIRED_TIME BIGINT NOT NULL, SCHED_TIME BIGINT NOT NULL, PRIORITY INT NOT NULL, STATE VARCHAR(16) NOT NULL, JOB_NAME VARCHAR(190) NULL, JOB_GROUP VARCHAR(190) NULL, IS_NONCONCURRENT VARCHAR(1) NULL, REQUESTS_RECOVERY VARCHAR(1) NULL, CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID));

-- changeset 82431:1666748033857-5
CREATE TABLE QRTZ_JOB_DETAILS (SCHED_NAME VARCHAR(120) NOT NULL, JOB_NAME VARCHAR(190) NOT NULL, JOB_GROUP VARCHAR(190) NOT NULL, `DESCRIPTION` VARCHAR(250) NULL, JOB_CLASS_NAME VARCHAR(250) NOT NULL, IS_DURABLE VARCHAR(1) NOT NULL, IS_NONCONCURRENT VARCHAR(1) NOT NULL, IS_UPDATE_DATA VARCHAR(1) NOT NULL, REQUESTS_RECOVERY VARCHAR(1) NOT NULL, JOB_DATA BLOB NULL, CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP));

-- changeset 82431:1666748033857-6
CREATE TABLE QRTZ_LOCKS (SCHED_NAME VARCHAR(120) NOT NULL, LOCK_NAME VARCHAR(40) NOT NULL, CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME));

-- changeset 82431:1666748033857-7
CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_GROUP VARCHAR(190) NOT NULL, CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP));

-- changeset 82431:1666748033857-8
CREATE TABLE QRTZ_SCHEDULER_STATE (SCHED_NAME VARCHAR(120) NOT NULL, INSTANCE_NAME VARCHAR(190) NOT NULL, LAST_CHECKIN_TIME BIGINT NOT NULL, CHECKIN_INTERVAL BIGINT NOT NULL, CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (SCHED_NAME, INSTANCE_NAME));

-- changeset 82431:1666748033857-9
CREATE TABLE QRTZ_SIMPLE_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(190) NOT NULL, TRIGGER_GROUP VARCHAR(190) NOT NULL, REPEAT_COUNT BIGINT NOT NULL, REPEAT_INTERVAL BIGINT NOT NULL, TIMES_TRIGGERED BIGINT NOT NULL, CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP));

-- changeset 82431:1666748033857-10
CREATE TABLE QRTZ_SIMPROP_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(190) NOT NULL, TRIGGER_GROUP VARCHAR(190) NOT NULL, STR_PROP_1 VARCHAR(512) NULL, STR_PROP_2 VARCHAR(512) NULL, STR_PROP_3 VARCHAR(512) NULL, INT_PROP_1 INT NULL, INT_PROP_2 INT NULL, LONG_PROP_1 BIGINT NULL, LONG_PROP_2 BIGINT NULL, DEC_PROP_1 DECIMAL(13, 4) NULL, DEC_PROP_2 DECIMAL(13, 4) NULL, BOOL_PROP_1 VARCHAR(1) NULL, BOOL_PROP_2 VARCHAR(1) NULL, CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP));

-- changeset 82431:1666748033857-11
CREATE TABLE QRTZ_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(190) NOT NULL, TRIGGER_GROUP VARCHAR(190) NOT NULL, JOB_NAME VARCHAR(190) NOT NULL, JOB_GROUP VARCHAR(190) NOT NULL, `DESCRIPTION` VARCHAR(250) NULL, NEXT_FIRE_TIME BIGINT NULL, PREV_FIRE_TIME BIGINT NULL, PRIORITY INT NULL, TRIGGER_STATE VARCHAR(16) NOT NULL, TRIGGER_TYPE VARCHAR(8) NOT NULL, START_TIME BIGINT NOT NULL, END_TIME BIGINT NULL, CALENDAR_NAME VARCHAR(190) NULL, MISFIRE_INSTR SMALLINT NULL, JOB_DATA BLOB NULL, CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP));

-- changeset 82431:1666748033857-12
CREATE TABLE basic_code_mapping (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL COMMENT '字典名称', note VARCHAR(500) NULL COMMENT '备注', items JSON(1073741824) NULL COMMENT '详情', create_by VARCHAR(20) NULL COMMENT '创建人', create_time datetime NULL COMMENT '创建时间', update_by VARCHAR(20) NULL COMMENT '最后修改人', update_time datetime NULL COMMENT '最后修改时间', tenant_id INT NOT NULL COMMENT '租户', deleted BIT(1) NULL, CONSTRAINT PK_BASIC_CODE_MAPPING PRIMARY KEY (id)) COMMENT='代码对照';
ALTER TABLE basic_code_mapping COMMENT = '代码对照';
ALTER TABLE basic_code_mapping MODIFY COLUMN name VARCHAR(50) COMMENT '字典名称';
ALTER TABLE basic_code_mapping MODIFY COLUMN note VARCHAR(500) COMMENT '备注';
ALTER TABLE basic_code_mapping MODIFY COLUMN items JSON(1073741824) COMMENT '详情';
ALTER TABLE basic_code_mapping MODIFY COLUMN create_by VARCHAR(20) COMMENT '创建人';
ALTER TABLE basic_code_mapping MODIFY COLUMN create_time datetime COMMENT '创建时间';
ALTER TABLE basic_code_mapping MODIFY COLUMN update_by VARCHAR(20) COMMENT '最后修改人';
ALTER TABLE basic_code_mapping MODIFY COLUMN update_time datetime COMMENT '最后修改时间';
ALTER TABLE basic_code_mapping MODIFY COLUMN tenant_id INT COMMENT '租户';

-- changeset 82431:1666748033857-13
CREATE TABLE basic_file (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(500) NOT NULL COMMENT '文件名称', object_name VARCHAR(100) NOT NULL COMMENT '文件key', url VARCHAR(1000) NOT NULL COMMENT '下载地址', related_type VARCHAR(30) NOT NULL COMMENT '类型，产品或者设备', related_id VARCHAR(100) NOT NULL COMMENT '关联产品或者设备的id', create_by VARCHAR(20) NULL, create_time datetime NULL, tenant_id INT NOT NULL, CONSTRAINT PK_BASIC_FILE PRIMARY KEY (id)) COMMENT='文件上传';
ALTER TABLE basic_file COMMENT = '文件上传';
ALTER TABLE basic_file MODIFY COLUMN name VARCHAR(500) COMMENT '文件名称';
ALTER TABLE basic_file MODIFY COLUMN object_name VARCHAR(100) COMMENT '文件key';
ALTER TABLE basic_file MODIFY COLUMN url VARCHAR(1000) COMMENT '下载地址';
ALTER TABLE basic_file MODIFY COLUMN related_type VARCHAR(30) COMMENT '类型，产品或者设备';
ALTER TABLE basic_file MODIFY COLUMN related_id VARCHAR(100) COMMENT '关联产品或者设备的id';

-- changeset 82431:1666748033857-14
CREATE TABLE basic_message_config (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL COMMENT '配置名称', type VARCHAR(30) NULL COMMENT '消息类型', provider VARCHAR(30) NULL COMMENT '服务提供商', config JSON(1073741824) NULL COMMENT '配置参数', create_by VARCHAR(20) NULL COMMENT '创建人', create_time datetime NULL COMMENT '创建时间', update_by VARCHAR(20) NULL COMMENT '最后修改人', update_time datetime NULL COMMENT '最后修改时间', deleted BIT(1) DEFAULT 0 NOT NULL COMMENT '1删除，0正常', tenant_id INT NOT NULL, CONSTRAINT PK_BASIC_MESSAGE_CONFIG PRIMARY KEY (id)) COMMENT='消息配置';
ALTER TABLE basic_message_config COMMENT = '消息配置';
ALTER TABLE basic_message_config MODIFY COLUMN name VARCHAR(50) COMMENT '配置名称';
ALTER TABLE basic_message_config MODIFY COLUMN type VARCHAR(30) COMMENT '消息类型';
ALTER TABLE basic_message_config MODIFY COLUMN provider VARCHAR(30) COMMENT '服务提供商';
ALTER TABLE basic_message_config MODIFY COLUMN config JSON(1073741824) COMMENT '配置参数';
ALTER TABLE basic_message_config MODIFY COLUMN create_by VARCHAR(20) COMMENT '创建人';
ALTER TABLE basic_message_config MODIFY COLUMN create_time datetime COMMENT '创建时间';
ALTER TABLE basic_message_config MODIFY COLUMN update_by VARCHAR(20) COMMENT '最后修改人';
ALTER TABLE basic_message_config MODIFY COLUMN update_time datetime COMMENT '最后修改时间';
ALTER TABLE basic_message_config MODIFY COLUMN deleted BIT(1) COMMENT '1删除，0正常';

-- changeset 82431:1666748033857-15
CREATE TABLE basic_message_template (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL COMMENT '模板名称', type VARCHAR(30) NULL COMMENT '消息类型', provider VARCHAR(30) NULL COMMENT '服务提供商', config JSON(1073741824) NULL COMMENT '配置参数', create_by VARCHAR(20) NULL COMMENT '创建人', create_time datetime NULL COMMENT '创建时间', update_by VARCHAR(20) NULL COMMENT '最后修改人', update_time datetime NULL COMMENT '最后修改时间', deleted BIT(1) DEFAULT 0 NOT NULL COMMENT '1删除，0正常', tenant_id INT NOT NULL, CONSTRAINT PK_BASIC_MESSAGE_TEMPLATE PRIMARY KEY (id)) COMMENT='消息模板';
ALTER TABLE basic_message_template COMMENT = '消息模板';
ALTER TABLE basic_message_template MODIFY COLUMN name VARCHAR(50) COMMENT '模板名称';
ALTER TABLE basic_message_template MODIFY COLUMN type VARCHAR(30) COMMENT '消息类型';
ALTER TABLE basic_message_template MODIFY COLUMN provider VARCHAR(30) COMMENT '服务提供商';
ALTER TABLE basic_message_template MODIFY COLUMN config JSON(1073741824) COMMENT '配置参数';
ALTER TABLE basic_message_template MODIFY COLUMN create_by VARCHAR(20) COMMENT '创建人';
ALTER TABLE basic_message_template MODIFY COLUMN create_time datetime COMMENT '创建时间';
ALTER TABLE basic_message_template MODIFY COLUMN update_by VARCHAR(20) COMMENT '最后修改人';
ALTER TABLE basic_message_template MODIFY COLUMN update_time datetime COMMENT '最后修改时间';
ALTER TABLE basic_message_template MODIFY COLUMN deleted BIT(1) COMMENT '1删除，0正常';

-- changeset 82431:1666748033857-16
CREATE TABLE core_device (id VARCHAR(50) NULL COMMENT '设备标识', secret VARCHAR(30) NULL COMMENT '设备秘钥', gateway_key VARCHAR(30) NULL COMMENT '网关设备key', name VARCHAR(50) NULL COMMENT '设备名称', product_id VARCHAR(20) NULL COMMENT '所属产品', status VARCHAR(20) NULL COMMENT '状态', tags JSON(1073741824) NULL COMMENT '标签', create_time datetime NULL, create_by VARCHAR(20) NULL, update_time datetime NULL, update_by VARCHAR(20) NULL, tenant_id INT NOT NULL, UNIQUE (id)) COMMENT='设备';
ALTER TABLE core_device COMMENT = '设备';
ALTER TABLE core_device MODIFY COLUMN id VARCHAR(50) COMMENT '设备标识';
ALTER TABLE core_device MODIFY COLUMN secret VARCHAR(30) COMMENT '设备秘钥';
ALTER TABLE core_device MODIFY COLUMN gateway_key VARCHAR(30) COMMENT '网关设备key';
ALTER TABLE core_device MODIFY COLUMN name VARCHAR(50) COMMENT '设备名称';
ALTER TABLE core_device MODIFY COLUMN product_id VARCHAR(20) COMMENT '所属产品';
ALTER TABLE core_device MODIFY COLUMN status VARCHAR(20) COMMENT '状态';
ALTER TABLE core_device MODIFY COLUMN tags JSON(1073741824) COMMENT '标签';

-- changeset 82431:1666748033857-17
CREATE TABLE core_product (id VARCHAR(20) NOT NULL COMMENT '产品key', secret VARCHAR(20) NOT NULL COMMENT '产品秘钥', name VARCHAR(50) NOT NULL COMMENT '产品名称', net_type VARCHAR(20) NOT NULL COMMENT '联网方式', metadata JSON(1073741824) NULL COMMENT '物模型', dynamic_register BIT(1) NULL COMMENT '动态注册', category_id INT NOT NULL COMMENT '品类', status VARCHAR(20) NOT NULL COMMENT '产品状态', tags JSON(1073741824) NULL COMMENT '产品标签', note VARCHAR(500) NULL COMMENT '产品描述', create_time datetime NULL, create_by VARCHAR(20) NULL, update_time datetime NULL, update_by VARCHAR(20) NULL, deleted BIT(1) NULL, tenant_id INT NOT NULL, UNIQUE (id)) COMMENT='产品';
ALTER TABLE core_product COMMENT = '产品';
ALTER TABLE core_product MODIFY COLUMN id VARCHAR(20) COMMENT '产品key';
ALTER TABLE core_product MODIFY COLUMN secret VARCHAR(20) COMMENT '产品秘钥';
ALTER TABLE core_product MODIFY COLUMN name VARCHAR(50) COMMENT '产品名称';
ALTER TABLE core_product MODIFY COLUMN net_type VARCHAR(20) COMMENT '联网方式';
ALTER TABLE core_product MODIFY COLUMN metadata JSON(1073741824) COMMENT '物模型';
ALTER TABLE core_product MODIFY COLUMN dynamic_register BIT(1) COMMENT '动态注册';
ALTER TABLE core_product MODIFY COLUMN category_id INT COMMENT '品类';
ALTER TABLE core_product MODIFY COLUMN status VARCHAR(20) COMMENT '产品状态';
ALTER TABLE core_product MODIFY COLUMN tags JSON(1073741824) COMMENT '产品标签';
ALTER TABLE core_product MODIFY COLUMN note VARCHAR(500) COMMENT '产品描述';

-- changeset 82431:1666748033857-18
CREATE TABLE core_product_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NULL, parent_id INT NULL, deleted INT DEFAULT 0 NULL, create_by VARCHAR(20) NULL, create_time datetime NULL, update_by VARCHAR(20) NULL, update_time datetime NULL, tenant_id INT NOT NULL, CONSTRAINT PK_CORE_PRODUCT_CATEGORY PRIMARY KEY (id)) COMMENT='产品品类';
ALTER TABLE core_product_category COMMENT = '产品品类';

-- changeset 82431:1666748033857-19
CREATE TABLE core_rule (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL COMMENT '规则名称', note VARCHAR(30) NULL COMMENT '规则描述', config JSON(1073741824) NULL COMMENT '详细配置', status VARCHAR(20) NULL COMMENT '状态', related_product_ids JSON(1073741824) NULL COMMENT '关联的产品id，根据规则自动填充', create_by VARCHAR(20) NULL COMMENT '创建人', create_time datetime NULL COMMENT '创建时间', update_by VARCHAR(20) NULL COMMENT '最后修改人', update_time datetime NULL COMMENT '最后修改时间', deleted BIT(1) DEFAULT 0 NOT NULL COMMENT '1删除，0正常', tenant_id INT NOT NULL, CONSTRAINT PK_CORE_RULE PRIMARY KEY (id)) COMMENT='规则';
ALTER TABLE core_rule COMMENT = '规则';
ALTER TABLE core_rule MODIFY COLUMN name VARCHAR(50) COMMENT '规则名称';
ALTER TABLE core_rule MODIFY COLUMN note VARCHAR(30) COMMENT '规则描述';
ALTER TABLE core_rule MODIFY COLUMN config JSON(1073741824) COMMENT '详细配置';
ALTER TABLE core_rule MODIFY COLUMN status VARCHAR(20) COMMENT '状态';
ALTER TABLE core_rule MODIFY COLUMN related_product_ids JSON(1073741824) COMMENT '关联的产品id，根据规则自动填充';
ALTER TABLE core_rule MODIFY COLUMN create_by VARCHAR(20) COMMENT '创建人';
ALTER TABLE core_rule MODIFY COLUMN create_time datetime COMMENT '创建时间';
ALTER TABLE core_rule MODIFY COLUMN update_by VARCHAR(20) COMMENT '最后修改人';
ALTER TABLE core_rule MODIFY COLUMN update_time datetime COMMENT '最后修改时间';
ALTER TABLE core_rule MODIFY COLUMN deleted BIT(1) COMMENT '1删除，0正常';

-- changeset 82431:1666748033857-20
CREATE TABLE sys_permission (id INT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, parent_id INT NULL, sort VARCHAR(2) NULL, CONSTRAINT PK_SYS_PERMISSION PRIMARY KEY (id), UNIQUE (id));

-- changeset 82431:1666748033857-21
CREATE TABLE sys_role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, note VARCHAR(200) NULL, create_by VARCHAR(20) NULL, create_time datetime NULL, update_by VARCHAR(20) NULL, update_time datetime NULL, tenant_id INT NULL, CONSTRAINT PK_SYS_ROLE PRIMARY KEY (id), UNIQUE (id)) COMMENT='角色';
ALTER TABLE sys_role COMMENT = '角色';

-- changeset 82431:1666748033857-22
CREATE TABLE sys_role_permission (id INT AUTO_INCREMENT NOT NULL, role_id INT NULL, permission_id INT NULL, CONSTRAINT PK_SYS_ROLE_PERMISSION PRIMARY KEY (id)) COMMENT='角色权限关联';
ALTER TABLE sys_role_permission COMMENT = '角色权限关联';

-- changeset 82431:1666748033857-23
CREATE TABLE sys_tenant (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL COMMENT '租户名称', note VARCHAR(500) NULL COMMENT '备注', status VARCHAR(30) NULL COMMENT '状态', admin_id INT NOT NULL COMMENT '管理员Id', create_by VARCHAR(20) NULL COMMENT '创建人', create_time datetime NULL COMMENT '创建时间', update_by VARCHAR(20) NULL COMMENT '最后修改人', update_time datetime NULL COMMENT '最后修改时间', deleted BIT(1) DEFAULT 0 NOT NULL COMMENT '1删除，0正常', CONSTRAINT PK_SYS_TENANT PRIMARY KEY (id)) COMMENT='租户管理';
ALTER TABLE sys_tenant COMMENT = '租户管理';
ALTER TABLE sys_tenant MODIFY COLUMN name VARCHAR(100) COMMENT '租户名称';
ALTER TABLE sys_tenant MODIFY COLUMN note VARCHAR(500) COMMENT '备注';
ALTER TABLE sys_tenant MODIFY COLUMN status VARCHAR(30) COMMENT '状态';
ALTER TABLE sys_tenant MODIFY COLUMN admin_id INT COMMENT '管理员Id';
ALTER TABLE sys_tenant MODIFY COLUMN create_by VARCHAR(20) COMMENT '创建人';
ALTER TABLE sys_tenant MODIFY COLUMN create_time datetime COMMENT '创建时间';
ALTER TABLE sys_tenant MODIFY COLUMN update_by VARCHAR(20) COMMENT '最后修改人';
ALTER TABLE sys_tenant MODIFY COLUMN update_time datetime COMMENT '最后修改时间';
ALTER TABLE sys_tenant MODIFY COLUMN deleted BIT(1) COMMENT '1删除，0正常';

-- changeset 82431:1666748033857-24
CREATE TABLE sys_user (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(20) NOT NULL COMMENT '用户类型', username VARCHAR(30) NOT NULL COMMENT '用户名', phone VARCHAR(30) NOT NULL COMMENT '电话', password VARCHAR(100) NOT NULL COMMENT '密码', name VARCHAR(30) NOT NULL COMMENT '姓名', status VARCHAR(30) NULL COMMENT '状态', create_by VARCHAR(20) NULL COMMENT '创建人', create_time datetime NULL COMMENT '创建时间', update_by VARCHAR(20) NULL COMMENT '最后修改人', update_time datetime NULL COMMENT '最后修改时间', deleted BIT(1) DEFAULT 0 NOT NULL COMMENT '1删除，0正常', tenant_id INT NULL COMMENT '租户', CONSTRAINT PK_SYS_USER PRIMARY KEY (id)) COMMENT='用户';
ALTER TABLE sys_user COMMENT = '用户';
ALTER TABLE sys_user MODIFY COLUMN type VARCHAR(20) COMMENT '用户类型';
ALTER TABLE sys_user MODIFY COLUMN username VARCHAR(30) COMMENT '用户名';
ALTER TABLE sys_user MODIFY COLUMN phone VARCHAR(30) COMMENT '电话';
ALTER TABLE sys_user MODIFY COLUMN password VARCHAR(100) COMMENT '密码';
ALTER TABLE sys_user MODIFY COLUMN name VARCHAR(30) COMMENT '姓名';
ALTER TABLE sys_user MODIFY COLUMN status VARCHAR(30) COMMENT '状态';
ALTER TABLE sys_user MODIFY COLUMN create_by VARCHAR(20) COMMENT '创建人';
ALTER TABLE sys_user MODIFY COLUMN create_time datetime COMMENT '创建时间';
ALTER TABLE sys_user MODIFY COLUMN update_by VARCHAR(20) COMMENT '最后修改人';
ALTER TABLE sys_user MODIFY COLUMN update_time datetime COMMENT '最后修改时间';
ALTER TABLE sys_user MODIFY COLUMN deleted BIT(1) COMMENT '1删除，0正常';
ALTER TABLE sys_user MODIFY COLUMN tenant_id INT COMMENT '租户';

-- changeset 82431:1666748033857-25
CREATE TABLE sys_user_role (id INT AUTO_INCREMENT NOT NULL, user_id INT NULL, role_id INT NULL, CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY (id)) COMMENT='用户角色关联';
ALTER TABLE sys_user_role COMMENT = '用户角色关联';

-- changeset 82431:1666748033857-26
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);

-- changeset 82431:1666748033857-27
CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, JOB_GROUP);

-- changeset 82431:1666748033857-28
CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, JOB_NAME, JOB_GROUP);

-- changeset 82431:1666748033857-29
CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, TRIGGER_GROUP);

-- changeset 82431:1666748033857-30
CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, INSTANCE_NAME);

-- changeset 82431:1666748033857-31
CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

-- changeset 82431:1666748033857-32
CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS(SCHED_NAME, JOB_GROUP);

-- changeset 82431:1666748033857-33
CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS(SCHED_NAME, REQUESTS_RECOVERY);

-- changeset 82431:1666748033857-34
CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS(SCHED_NAME, CALENDAR_NAME);

-- changeset 82431:1666748033857-35
CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_GROUP);

-- changeset 82431:1666748033857-36
CREATE INDEX IDX_QRTZ_T_J ON QRTZ_TRIGGERS(SCHED_NAME, JOB_NAME, JOB_GROUP);

-- changeset 82431:1666748033857-37
CREATE INDEX IDX_QRTZ_T_JG ON QRTZ_TRIGGERS(SCHED_NAME, JOB_GROUP);

-- changeset 82431:1666748033857-38
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(SCHED_NAME, NEXT_FIRE_TIME);

-- changeset 82431:1666748033857-39
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);

-- changeset 82431:1666748033857-40
CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);

-- changeset 82431:1666748033857-41
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);

-- changeset 82431:1666748033857-42
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);

-- changeset 82431:1666748033857-43
CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);

-- changeset 82431:1666748033857-44
CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);

-- changeset 82431:1666748033857-45
CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_STATE);

-- changeset 82431:1666748033857-46
ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT QRTZ_BLOB_TRIGGERS_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset 82431:1666748033857-47
ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT QRTZ_CRON_TRIGGERS_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset 82431:1666748033857-48
ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT QRTZ_SIMPLE_TRIGGERS_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset 82431:1666748033857-49
ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT QRTZ_SIMPROP_TRIGGERS_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset 82431:1666748033857-50
ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT QRTZ_TRIGGERS_ibfk_1 FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP) ON UPDATE RESTRICT ON DELETE RESTRICT;

