spring:
  datasource:
    url: jdbc:mysql://192.168.82.50:3306/liquibase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root

  liquibase:
    change-log: classpath:/db/master.xml