spring:
  datasource:
    url: jdbc:mysql://172.27.71.24:3306/liquibase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root

  liquibase:
    change-log: classpath:/db/changelog_master.xml